# Generated by Django 5.1.4 on 2024-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
